### ISSUE TITLE
Chocolately install

### ISSUE THREAD

**Issue by claremacrae** [philhansen/WallpaperChanger#4]
Would you consider providing an install on [chocolatey](https://chocolatey.org) please?

/cc @isidore

**Comment by philhansen** [comment]
Thanks for the suggestion and sorry for the delay in getting back to you!  At this time I do not have any plans to pursue something like this.

WallpaperChanger is a tiny app that I do not personally use anymore.  I have primarily just been keeping it updated for each new version of windows.

**Comment by claremacrae** [comment]
Hi Phil, Many thanks for the reply - much appreciated.
