### ISSUE TITLE
Suggestion of improvement

### ISSUE THREAD

**Issue by Dragodraki** [philhansen/WallpaperChanger#5]
Your app is very useful.
I continued your work a little bit to got some better error handling and show the original image display name as theme when open explorer.exe shell:::{ED834ED6-4B5A-4bfe-8F11-A626DCB6A921}.
Maybe you'd like to take a look at it and publish it by yourself (I didn't changed any runtime packages or other dependendies - compiled with VS 2017 and verified working on Windows XP/7)
[WallpaperChanger-master_1.9.zip](https://github.com/philhansen/WallpaperChanger/files/11991084/WallpaperChanger-master_1.9.zip)

Since this isn't about an issue, you can close it immedtiately (or I can do).

**Comment by philhansen** [comment]
Hi Dragodraki, I no longer use this app but I welcome any PRs.  Do you want to create a PR for your changes and I can take a look?

**Comment by MatheusGrion** [comment]
Quem quiser em Pt-Br , vou deixar aqui em baixo.

<?xml version="1.0" encoding="utf-8"?>
<language culture="Pt-Br">
  <author>MatheusGrion</author>
  <version>1.0</version>
  <messages>
    <message name="MBox_CreateThemeFirst" value="Crie um tema primeiro!" />
    <message name="MBox_UnableRegisterHotKey" value="Não é possível registrar a tecla de atalho para a troca de papéis de parede.&#xA;A tecla de atalho {0} está atribuída a algum outro evento." />
    <message name="MBox_SuccesRegisterHotKey" value="Tecla de atalho {0} registrada com sucesso para a troca de papéis de parede." />
    <message name="MBox_UpdateThemeNow" value="Atualizar tema {0} agora?" />
    <message name="MBox_Update" value="Atualizar" />
    <message name="MBox_YouHaveCurrentVersion" value="Você tem a versão atual" />
    <message name="TotalWall" value="Total de papéis de parede = " />
    <message name="CurrentWall" value=", papéis de parede atuais = " />
    <message name="Ball_NoCurrWall" value="Nenhum papel de parede atual!" />
    <message name="Ball_NoNextWall" value="Nenhum próximo papel de parede!" />
    <message name="Ball_NoPrevWall" value="Nenhum papel de parede anterior!" />
    <message name="Ball_WallSetSucces" value="Papel de parede {0} definido com sucesso." />
    <message name="Ball_WallNotSet" value="Papel de parede {0} não definido!" />
    <message name="None" value="(nenhum)" />
    <message name="NextChangeAt" value="Próxima mudança em " />
    <message name="NotActive" value="Não Ativo" />
    <message name="MBox_FileAlreadyInListView" value="Arquivo já na Lista de Visualização!" />
    <message name="MBox_DirAlreadyInListView" value="Diretório já na Lista de Visualização!" />
    <message name="NewTheme" value="Novo Tema" />
    <message name="NewThemePrompt" value="Digite um nome para o novo tema:" />
    <message name="RenameTheme" value="Renomear Tema" />
    <message name="RenameThemePrompt" value="Digite o novo nome para o tema:" />
    <message name="MBox_RenameThemeNewName" value="Renomear Tema em &quot;{0}&quot;?" />
    <message name="DuplicateTheme" value="Duplicar Tema" />
    <message name="DuplicateThemePrompt" value="Digite o novo nome para o tema duplicado:" />
    <message name="MBox_ThemeWithNameExist" value="Tema com o nome &quot;{0}&quot; já existe!" />
    <message name="MBox_DeleteLastTheme" value="Você não pode excluir o último tema na lista. Deve haver pelo menos um tema presente." />
<message name="MBox_Warning" value="Aviso" />
<message name="MBox_DeleteThemeQuest" value="Tem certeza de que deseja excluir o tema '{0}'?" />
<message name="MBox_DeleteTheme" value="Excluir Tema?" />
<message name="MBox_NoCurrTheme" value="Nenhum tema atual!" />
<message name="MBox_FileNotExist" value="Arquivo {0} não existe!" />
<message name="MBox_NotZeroInterval" value="É necessário definir um intervalo de mudança de papel de parede diferente de zero." />
<message name="MBox_NotExist" value="{0} não existe!" />
<message name="NewVersionReleased" value="Nova versão {0} lançada" />
<message name="Version" value="Versão:" />
<message name="Version2" value="Versão {0}" />
<message name="About" value="Sobre {0}" />
<message name="BuildOn" value="Construído em: {0} {1}" />
<message name="MBox_SettingsReadError" value="Ocorreu um erro ao ler o arquivo de configurações." />
<message name="MBox_RestoringSettingsFromBackup" value="Arquivo de configurações restaurado de um arquivo de backup." />
<message name="MBox_ThemesReadError" value="Ocorreu um erro ao ler o arquivo de temas." />
<message name="MBox_RestoringThemesFromBackup" value="Arquivo de temas restaurado de um arquivo de backup." />
<message name="Crash_UnknownError" value="Ocorreu um erro desconhecido. WallpaperChanger não pode continuar." />
<message name="Crash_ErrorReportSent" value="Relatório de erro enviado. Obrigado por ajudar a melhorar " />
<message name="Crash_ SendingReportFailed" value="Falha no envio do relatório." />
<message name="Theme" value="Tema" />
<message name="PerformanceSave" value="Operação de salvamento de desempenho..." />
</messages>
<forms>
<form type="WallpaperChanger.FormMain">
<component name="cmTray_LastUpdatedWallLabel" value="Último papel de parede atualizado:" />
<component name="cmTray_LastUpdatedWall" value="(nenhum)" />
<component name="cmTray_ActiveChanging" value="Ativação de mudança" />
<component name="cmTray_Settings" value="Configurações" />
<component name="cmTray_Theme" value="Tema" />
<component name="cmTray_HideDesktopIcon" value="Ocultar ícones da área de trabalho" />
<component name="cmTray_NextWall" value="Próximo papel de parede" />
<component name="cmTray_PrevWall" value="Papel de parede anterior" />
<component name="cmTray_Exit" value="Sair" />
<tooltip name="listViewLocations" value="Adicione arquivo ou diretório com papéis de parede" />
<tooltip name="buttonRegisterHotKey" value="Registrar tecla de atalho no sistema" />
<tooltip name="buttonRefrech" value="Atualizar papel de parede atual" />
<tooltip name="buttonNext" value="Próximo papel de parede" />
<tooltip name="buttonStart" value="Iniciar mudança" />
<tooltip name="buttonPrevious" value="Papel de parede anterior" />
<tooltip name="buttonMirrorHor" value="Virar horizontalmente" />
<tooltip name="buttonMirrorVer" value="Virar verticalmente" />
<property name="toolStripMenuItem_File.Text" value="Arquivo" />
<property name="toolStripMenuItem_FileNewTheme.Text" value="Novo Tema" />
<property name="toolStripMenuItem_FileRenameTheme.Text" value="Renomear Tema" />
<property name="toolStripMenuItem_FileDuplicateTheme.Text" value="Duplicar Tema" />
<property name="toolStripMenuItem_FileUpdateTheme.Text" value="Atualizar Tema" />
<property name="toolStripMenuItem_FileResetWallCount.Text" value="Redefinir contagem de papéis de parede" />
<property name="toolStripMenuItem_FileDeleteTheme.Text" value="Excluir Tema" />
<property name="toolStripMenuItem_FileSaveTheme.Text" value="Salvar Temas" />
<property name="toolStripMenuItem_FileExit.Text" value="Sair" />
<property name="toolStripMenuItem_Help.Text" value="Ajuda" />
<property name="toolStripMenuItem_Language.Text" value="Idioma" />
<property name="toolStripMenuItem_HelpCheckUpdate.Text" value="Verificar atualizações" />
<property name="toolStripMenuItem_HelpAbout.Text" value="Sobre" />
<property name="tabPageWall.Text" value="Papéis de Parede" />
<property name="toolStripMenuItem_WallFiles.Text" value="Arquivos..." />
<property name="toolStripMenuItem_WallDirectory.Text" value="Diretório..." />
<property name="toolStripMenuItem_WallOpen.Text" value="Abrir" />
<property name="toolStripMenuItem_WallExplore.Text" value="Explorar" />
<property name="toolStripMenuItem_WallSetAsWall.Text" value="Definir como papel de parede" />
<property name="toolStripMenuItem_WallDelete.Text" value="Excluir" />
<property name="tabPageThemeSettings.Text" value="Configuração de Tema" />
<property name="grpDisplayMode.Text" value="Modo de Exibição" />
<property name="comboBoxWallTypeChange.Items" value="Sequencial" />
<property name="comboBoxWallTypeChange.Items" value="Random" />
<property name="checkBoxCyclingWallChange.Text" value="Mudança de papel de parede cíclica" />
<property name="checkBoxResizeTaskbar.Text" value="Redimensionar a barra de tarefas" />
<property name="labelChanging.Text" value="Mudança:" />
<property name="labelStyle.Text" value="Estilo:" />
<property name="labelPx.Text" value="px :" />
<property name="comboBoxSmallWallStyle.Items" value="Centro" />
<property name="comboBoxSmallWallStyle.Items" value="Mosaico" />
<property name="comboBoxSmallWallStyle.Items" value="Esticar" />
<property name="comboBoxSmallWallStyle.Items" value="Ajustar (redimensionado mantendo a proporção)" />
<property name="comboBoxSmallWallStyle.Items" value="Preencher (redimensionado e recortado mantendo a proporção)" />
<property name="comboBoxSmallWallStyle.Items" value="Não definido" />
<property name="labelImageLess.Text" value="Para imagens = a" />
<property name="comboBoxWallStyle.Items" value="Centro" />
<property name="comboBoxWallStyle.Items" value="Mosaico" />
<property name="comboBoxWallStyle.Items" value="Esticar" />
<property name="comboBoxWallStyle.Items" value="Ajustar (redimensionado mantendo a proporção)" />
<property name="comboBoxWallStyle.Items" value="Preencher (redimensionado e recortado mantendo a proporção)" />
<property name="grpFrequency.Text" value="Frequência de Mudança" />
<property name="checkBoxChangeOnceADay.Text" value="Não mais de uma vez por dia" />
<property name="seconds.Text" value="Segundos" />
<property name="minutes.Text" value="Minutos" />
<property name="days.Text" value="Dias" />
<property name="hours2.Text" value="Horas" />
<property name="checkBoxStartupChange.Text" value="Mudar o papel de parede na inicialização do programa" />
<property name="lblFrequency.Text" value="Mudar o papel de parede a cada" />
<property name="groupBoxBackgoundColor.Text" value="Cor de Fundo" />
<property name="labelLinearGradientMode.Text" value="Modo de Gradiente Linear:" />
<property name="comboBoxLinearGradientMode.Items" value="Horizontal" />
<property name="comboBoxLinearGradientMode.Items" value="Vertical" />
<property name="comboBoxLinearGradientMode.Items" value="Diagonal para a Frente" />
<property name="comboBoxLinearGradientMode.Items" value="Diagonal para Trás" />
<property name="labelBackgroundColour.Text" value="Cor de Fundo:" />
<property name="labelGradientColour.Text" value="Segunda Cor de Gradiente:" />
<property name="labelTypeBackground.Text" value="Tipo de Fundo:" />
<property name="comboBoxTypeBackground.Items" value="automático" />
<property name="comboBoxTypeBackground.Items" value="cor única" />
<property name="comboBoxTypeBackground.Items" value="gradiente" />
<property name="comboBoxTypeBackground.Items" value="esticar bordas" />
<property name="tabPage1.Text" value="Configuração" />
<property name="checkBoxBackupSettings.Text" value="Backup de configurações e temas na mudança" />
<property name="labelSeconds.Text" value="Segundos" />
<property name="labelMinutes.Text" value="Minutos" />
<property name="checkBoxDontChangeOnIdle.Text" value="Não mude em inatividade por mais de" />
<property name="checkBoxShowBalloon.Text" value="Mostrar notificação de Balão" />
<property name="comboBoxUpdateInterval.Items" value="dia" />
<property name="comboBoxUpdateInterval.Items" value="semana" />
<property name="comboBoxUpdateInterval.Items" value="mês" />
<property name="checkBoxUpdateCheck.Text" value="Verificar atualização uma vez a cada" />
<property name="checkBoxUseVistaWallResizer.Text" value="Usar redimensionador de papel de parede Vista" />
<property name="checkBoxCPULoad.Text" value="Não mude o papel de parede com carga da CPU maior que" />
<property name="checkBoxDeleteFilesOnLoad.Text" value="Excluir arquivo/diretório que não existir dos temas na inicialização do programa" />
<property name="groupBoxHotKey.Text" value="Tecla de Atalho" />
<property name="buttonRegisterHotKey.Text" value="Registrar" />
<property name="labelHotkeyToChange.Text" value="Tecla de atalho para mudar o papel de parede:" />
<property name="checkBoxEnableHotkeys.Text" value="Ativar teclas de atalho" />
<property name="checkBoxStartWithWindows.Text" value="Iniciar com o Windows" />
<property name="grpTheme.Text" value="Tema" />
</form>
<form type="WallpaperChanger.FormAbout">
<property name="Text" value="Sobre WallpaperChanger" />
</form>
<form type="WallpaperChanger.FormUpdate">
<property name="Text" value="Atualizar" />
</form>
<form type="WallpaperChanger.CrashReport">
<property name="Text" value="Relatório de Erros" />
<property name="tabPage1.Text" value="Exceção" />
<property name="label2.Text" value="Opcionalmente, você pode adicionar qualquer informação adicional que considerar apropriada, como o que estava tentando fazer na época. Você pode incluir seu endereço de e-mail se desejar que os autores entrem em contato com você. Você também pode deixar este campo em branco." />
<property name="label1.Text" value="Ajude-nos a tornar o WallpaperChanger um programa melhor, relatando este erro. Basta clicar em Enviar Relatório de Erro e as informações mostradas abaixo serão enviadas. Relatar este erro ajudará os autores a corrigir esse problema nas futuras versões." />
<property name="tabPage2.Text" value="Captura de Tela" />
<property name="linkLabelView.Text" value="Visualizar Captura de Tela Completa" />
<property name="groupBoxScreenshot.Text" value="Captura de Tela" />
<property name="checkBoxIncludeScreenshot.Text" value="Incluir Captura de Tela" />
<property name="checkBoxRestart.Text" value="Reiniciar o Programa" />
<property name="buttonDontSend.Text" value="Não Enviar" />
<property name="buttonSend.Text" value="Enviar Relatório de Erro" />
</form>
</forms>
</language>
